add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 8
truncate_to_repo = true
style = "bold #5878B7"

[git_branch]
symbol = "git:"
style = "bold #AF61D1"
format = "[$symbol$branch( -> $remote_name/$remote_branch)]($style)"

[git_status]
style = "bold #66BABC"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "~${count}"
ahead = "a${count}"
behind = "b${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
renamed = "->"
deleted = "x"

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold #72498D) "

[character]
success_symbol = "[> ](bold green)"
error_symbol = "[> ](bold red)"